# Docker Compose configuration for production environment
version: '3.8'

services:
  backend:
    build:
      target: production
    container_name: ticket-system-backend-prod
    restart: always
    environment:
      - ENVIRONMENT=production
    env_file:
      - ./backend/.env.production
    ports:
      - "8000:8000"
    volumes:
      - ./backend/logs:/app/logs:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ticket-system-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    container_name: ticket-system-nginx-prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx:rw
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ticket-system-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  ticket-system-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  backend_logs_prod:
    driver: local
  nginx_logs_prod:
    driver: local